### ISSUE TITLE
Having an activity with ZIO effect breaks type safety and requires wrapping errors with try

### ISSUE THREAD

**Issue by carlosedp** [vitaliihonta/zio-temporal#34]
When creating activities with ZIO effects that might fail, the return value of `ZActivity.run` is `Either[Failure,Success]`. 

```scala
@activityInterface
trait EchoActivity:
  @activityMethod
  def echo(msg: String): Either[Exception, String]

// Activity Implementation
class EchoActivityImpl(
  implicit options: ZActivityOptions[Any],
) extends EchoActivity:
  override def echo(msg: String): Either[Exception, String] =
    ZActivity.run:
      for
        _ <- ZIO.logDebug(s"Received message: $msg")
        newMsg <- eventuallyFail(s"ACK: $msg", 30)
      yield newMsg
      // This returns a ZIO[Any, Exception, String] which is mapped to an Either in `.run`
```

Like above, having the return values in my activity signature (which is required) and implementation as `Either[Failure,Success]`, throw a Temporal serialization error:

```
timestamp=2023-03-21T09:24:04.549352-03:00 level=ERROR thread=zio-fiber-0 message="" cause=Exception in thread "zio-fiber-6" zio.temporal.TemporalClientError: TemporalClientError(io.temporal.client.WorkflowFailedException: Workflow execution {workflowId='echo-b3794948-b558-48ab-a76d-8dacadabe3b4', runId='6ce905f5-a64c-415b-bedf-7ed575bf625c', workflowType='EchoWorkflow'} failed. Metadata: {closeEventType='EVENT_TYPE_WORKFLOW_EXECUTION_FAILED', retryState='RETRY_STATE_RETRY_POLICY_NOT_SET', workflowTaskCompletedEventId=10'} cause=io.temporal.failure.ApplicationFailure: message='class java.util.LinkedHashMap cannot be cast to class scala.util.Either (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; scala.util.Either is in unnamed module of loader 'app')', type='java.lang.ClassCastException', nonRetryable=false)
	at zio.temporal.internal.TemporalInteraction$.fromFuture.macro(TemporalInteraction.scala:27)
	at zio.temporal.internal.TemporalInteraction$.fromFuture.macro(TemporalInteraction.scala:28)
	at <empty>.Client.workflowResultZIO(zio-temporal-activity-retry.scala:125)
	at zio.temporal.worker.ZWorkerFactory.use.macro(ZWorkerFactory.scala:27)
	at zio.temporal.worker.ZWorkerFactory.use.macro(ZWorkerFactory.scala:28)
	at <empty>.Main.run.program(zio-temporal-activity-retry.scala:142)
	at <empty>.Main.run(zio-temporal-activity-retry.scala:144)
```

The workaround is defining the signature as `Any` like:

```scala
@activityInterface
trait EchoActivity:
  @activityMethod
  def echo(msg: String): Any

// Activity Implementation
class EchoActivityImpl(
  implicit options: ZActivityOptions[Any],
) extends EchoActivity:
  override def echo(msg: String): Any =
    ZActivity.run:
      for
        _ <- ZIO.logDebug(s"Received message: $msg")
        newMsg <- eventuallyFail(s"ACK: $msg", 30)
      yield newMsg
```

Which kinda works but the return value from Temporal is still an Either wrapped in json as seen in the logs below requiring something like a cast to extract the correct value.

```
❯ scli zio-temporal-activity-retry.scala
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
timestamp=2023-03-21T09:22:42.818928-03:00 level=INFO thread=zio-fiber-7 message="Started sample-worker"
timestamp=2023-03-21T09:22:43.165645-03:00 level=INFO thread=zio-fiber-6 message="Will submit message "testMsg""
timestamp=2023-03-21T09:22:43.427282-03:00 level=DEBUG thread=zio-fiber-27 message="Received message: testMsg"
timestamp=2023-03-21T09:22:43.523249-03:00 level=INFO thread=zio-fiber-6 message="The workflow result: {value=ACK: testMsg, left=false, right=true}"
```

The full code is in https://gist.github.com/carlosedp/61703d5c436dc50ec5876249fbbbed31

**Comment by carlosedp** [comment]
Might be also related to this issue but when the number of retries is reached, the following error is thrown in the worker side (I catch this in the client side separately).

Apparently also related to the encoding of the `Either` return.

```
timestamp=2023-03-22T11:33:29.958646-03:00 level=ERROR thread=zio-fiber-17469 message="Workflow execution failure WorkflowId=echo-63e77c7f-2204-40c7-bfbb-d4b579fa1ff7, RunId=fc9f0148-d105-48e4-9aa4-91592eae3ced, WorkflowType=EchoWorkflow" cause=Exception in thread "zio-fiber-" io.temporal.failure.ActivityFailure: scheduledEventId=5, startedEventId=6, activityType='Echo', activityId='313abce4-e317-3c55-923b-566a7a2cd762', identity='94513@CarlosEDP-MBP16.internal.carlosedp.com', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:49)
	at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:78)
	at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:71)
	at jdk.proxy1/jdk.proxy1.$Proxy13.echo(Unknown Source)
	at EchoWorkflowImpl.getEcho(EchoWorkflow.scala:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:310)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:285)
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:68)
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:135)
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102)
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107)
	at io.temporal.worker.WorkerFactory.lambda$newWorkflowThreadExecutor$7(WorkerFactory.java:392)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: io.temporal.failure.ApplicationFailure: message='com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class scala.runtime.BoxedUnit and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: scala.util.Right["value"])', type='io.temporal.common.converter.DataConverterException', nonRetryable=false
		at io.temporal.common.converter.JacksonJsonPayloadConverter.toData(JacksonJsonPayloadConverter.java:74)
		at io.temporal.common.converter.DefaultDataConverter.toPayload(DefaultDataConverter.java:119)
		at io.temporal.common.converter.DefaultDataConverter.toPayloads(DefaultDataConverter.java:159)
		at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.complete(ManualActivityCompletionClientImpl.java:102)
		at io.temporal.internal.sync.ActivityCompletionClientImpl.complete(ActivityCompletionClientImpl.java:50)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method:0)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at io.temporal.internal.WorkflowThreadMarker.lambda$protectFromWorkflowThread$1(WorkflowThreadMarker.java:83)
		at jdk.proxy1/jdk.proxy1.$Proxy2.complete(Unknown Source:0)
		at zio.temporal.activity.ZActivity$.run$$anonfun$5(ZActivity.scala:84)
		at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
		at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
		at zio.temporal.internal.ZioUnsafeFacade$.unsafeRunAsyncZIO$$anonfun$1$$anonfun$1(ZioUnsafeFacade.scala:32)
		at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
		at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
		Suppressed: io.temporal.failure.ApplicationFailure: message='No serializer found for class scala.runtime.BoxedUnit and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: scala.util.Right["value"])', type='com.fasterxml.jackson.databind.exc.InvalidDefinitionException', nonRetryable=false
			at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
			at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
			at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
			at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:46)
			at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:29)
			at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
			at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
			at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
			at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
			at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
			at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
			at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3844)
			at io.temporal.common.converter.JacksonJsonPayloadConverter.toData(JacksonJsonPayloadConverter.java:66)
			at io.temporal.common.converter.DefaultDataConverter.toPayload(DefaultDataConverter.java:119)
			at io.temporal.common.converter.DefaultDataConverter.toPayloads(DefaultDataConverter.java:159)
			at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.complete(ManualActivityCompletionClientImpl.java:102)
			at io.temporal.internal.sync.ActivityCompletionClientImpl.complete(ActivityCompletionClientImpl.java:50)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method:0)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
			at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.base/java.lang.reflect.Method.invoke(Method.java:568)
			at io.temporal.internal.WorkflowThreadMarker.lambda$protectFromWorkflowThread$1(WorkflowThreadMarker.java:83)
			at jdk.proxy1/jdk.proxy1.$Proxy2.complete(Unknown Source:0)
			at zio.temporal.activity.ZActivity$.run$$anonfun$5(ZActivity.scala:84)
			at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
			at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
			at zio.temporal.internal.ZioUnsafeFacade$.unsafeRunAsyncZIO$$anonfun$1$$anonfun$1(ZioUnsafeFacade.scala:32)
			at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
			at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)

```

**Comment by vitaliihonta** [comment]
Thank you for submitting it! 
That's definitely a serialization issue, but the root cause is the error model used in zio-temporal. Hope to fix this in #33 
Will come back to fix it later.

As a workaround, try wrapping Exception in Either into a case class and add jackson-module-scala in order to serialize Either properly. You may copy the approach from this #36 (see JacksonDataConverter)

**Comment by carlosedp** [comment]
Awesome, I was investigating more last week and got a similar solution.. I found jackson missed the scala module serialization... 
I had to add some imports for Jackson itself and configured the clientOptions as:

```scala
  val clientOptions: ULayer[ZWorkflowClientOptions] = ZLayer.succeed:
    ZWorkflowClientOptions.default.withDataConverter(
          new DefaultDataConverter(
              new JacksonJsonPayloadConverter(
                JsonMapper
                  .builder()
                  .addModule(DefaultScalaModule)
                  .build()
              )
          )
        )
```

And got it to work since fastxml now knows how to wrap Eithers (the Scala types). I just think maybe the default `ZWorkflowClientOptions` could have the standard converters like:

```scala
    workflowClientOptions = ZWorkflowClientOptions.default.withDataConverter(
      new DefaultDataConverter(
        // order matters!
        Seq(
          new NullPayloadConverter(),
          new ByteArrayPayloadConverter(),
          new ProtobufJsonPayloadConverter(),
          new JacksonJsonPayloadConverter(
            JsonMapper
              .builder()
              .addModule(DefaultScalaModule)
              .build()
          )
        ): _*
      )
    ),
```

**Comment by carlosedp** [comment]
I've pushed https://github.com/vitaliihonta/zio-temporal/pull/37 fixing this.
