### ISSUE TITLE
Lib cannot load .proto files when using scalapb plugin thru Mill build tool

### ISSUE THREAD

**Issue by carlosedp** [vitaliihonta/zio-temporal#35]
I use Mill as a build tool and while looking into protobuf usage in zio-temporal, I faced an error that generates encoding errors. Found-out zio-temporal could not load the proto file from my project.

I replicated the build.sbt file from https://github.com/vitaliihonta/func-scala-2022-zio-temporal to a build.sc (mill build file) and saw it doesn't load as seen in the logs below.

This issue is more of a question on how to debug this in the Mill build to fix it's scalapb plugin. Where does this proto loading comes from? The scalapb path?

```
❯ ./mill -i show cryptostock.run
[1/1] show
[1/1] show > [68/68] cryptostock.run
SLF4J: A number (19) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
15:39:57.697 [ZScheduler-Worker-6] TRACE z.t.p.i.ProtoFileObjectAutoLoader$ - Provided exclude prefixes: [org/scalatools/,com.google.protobuf,com/google/type/,sbt,com.uber.m3,gogoproto/,com.google.geo,magnolia,org/codehaus/mojo/,com/google/longrunning/,com.cronutils,com.google.thirdparty,xsbt/,com.typesafe.config,distage,com/google/rpc/,logstage/,com/google/common/,akka/,com/thoughtworks/,com.google.logging,org/checkerframework/,zio/temporal/,org.slf4j,com/sun/,io/perfmark/,akka,android/,io.temporal,org.checkerframework,sun,com.google.api,com/google/errorprone/,com/cronutils/,org.scalatools,com/google/geo/,com.google.rpc,com.sun,org.LatencyUtils,izumi,org.reflections,com.google.errorprone,xsbti,xsbti/,sbt/,com/fasterxml/,logstage,pureconfig/,pureconfig,scala/,org/reflections/,com.thoughtworks,com/google/protobuf/,java,com/google/cloud/,com.google.common,com/uber/m3/,jdk/,cats/,izumi/,com.google.longrunning,javax,org/LatencyUtils/,org/slf4j/,org.codehaus.mojo,com.google.gson,org.HdrHistogram,com/google/logging/,com/google/gson/,com/typesafe/config/,io.grpc,zio,xsbt,net/sf/cglib/,io/micrometer/,com.google.type,javax/,com/google/api/,scala,magnolia/,zio/,sun/,io.micrometer,org/HdrHistogram/,com/google/thirdparty/,io.perfmark,mercator,io/temporal/,com.google.cloud,zio.temporal,cats,mercator/,META-INF,org/apache/ivy/,java/,org.apache.ivy,distage/,io/grpc/,com.fasterxml,jdk,module-info.class,META-INF/,gogoproto,android,net.sf.cglib]
15:39:57.719 [ZScheduler-Worker-6] INFO  org.reflections.Reflections - Reflections took 8 ms to scan 0 urls, producing 0 keys and 0 values
15:39:57.728 [ZScheduler-Worker-6] TRACE z.t.p.i.ProtoFileObjectAutoLoader$ - Found subtypes of GeneratedFileObject: []
15:39:57.729 [ZScheduler-Worker-6] INFO  z.t.p.i.ProtoFileObjectAutoLoader$ - Loaded 0 GeneratedFileObject(s): []
15:39:57.916 [zio-default-blocking-1] INFO  i.t.s.WorkflowServiceStubsImpl - Created WorkflowServiceStubs for channel: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=1, target=127.0.0.1:7233}}
timestamp=2023-04-17T18:39:58.476190Z level=INFO thread=#zio-fiber-6 message="Going to create an exchange order" location=com.cryptostock.Main$.run.exampleFlow.macro file=Main.scala line=19
15:39:58.486 [zio-default-blocking-2] INFO  zio-slf4j-logger - timestamp=2023-04-17T15:39:58.483441-03:00 level=INFO thread=zio-fiber-6 message="Going to create an exchange order"
timestamp=2023-04-17T18:39:58.510999Z level=INFO thread=#zio-fiber-6 message="Going to trigger workflow" location=com.cryptostock.clients.ExchangeClientService.exchangeOrder.macro file=ExchangeClientService.scala line=39
15:39:58.511 [zio-default-blocking-2] INFO  zio-slf4j-logger - timestamp=2023-04-17T15:39:58.511369-03:00 level=INFO thread=zio-fiber-6 message="Going to trigger workflow"
timestamp=2023-04-17T18:39:58.600419Z level=INFO thread=#zio-fiber-6 message="Order placed" location=com.cryptostock.Main$.run.exampleFlow.macro file=Main.scala line=24
15:39:58.601 [zio-default-blocking-2] INFO  zio-slf4j-logger - timestamp=2023-04-17T15:39:58.600896-03:00 level=INFO thread=zio-fiber-6 message="Order placed"
15:39:58.726 [workflow-method-10b07a55-347f-4119-9b59-b1e4edffcc14-53a41b05-e116-4b6e-9af1-d92f2cf6c16c] ERROR i.t.i.sync.WorkflowExecuteRunnable - Workflow execution failure WorkflowId=10b07a55-347f-4119-9b59-b1e4edffcc14, RunId=53a41b05-e116-4b6e-9af1-d92f2cf6c16c, WorkflowType=ExchangeWorkflow
io.temporal.common.converter.DataConverterException: Unable to convert metadata {
  key: "encoding"
  value: "binary/protobuf"
}
metadata {
  key: "messageType"
  value: "com.cryptostock.exchange.ExchangeOrderRequest"
}
data: "\n\022\t\344N\026\214\235!\315\356\021\307\220#\267;$\027\252\022\b\b\001\022\004\n\002\001\244\030\000"
 to com.cryptostock.exchange.ExchangeOrderRequest when parsing:"
	�N��!��ǐ#�;$�
�" into following types: [class com.cryptostock.exchange.ExchangeOrderRequest]
	at io.temporal.common.converter.DefaultDataConverter.fromPayload(DefaultDataConverter.java:140)
	at io.temporal.common.converter.DataConverter.arrayFromPayloads(DataConverter.java:105)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:278)
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:68)
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:135)
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102)
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107)
	at io.temporal.worker.WorkerFactory.lambda$newWorkflowThreadExecutor$7(WorkerFactory.java:392)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: zio.temporal.protobuf.ProtobufPayloadException: Unable to convert metadata {
  key: "encoding"
  value: "binary/protobuf"
}
metadata {
  key: "messageType"
  value: "com.cryptostock.exchange.ExchangeOrderRequest"
}
data: "\n\022\t\344N\026\214\235!\315\356\021\307\220#\267;$\027\252\022\b\b\001\022\004\n\002\001\244\030\000"
 to com.cryptostock.exchange.ExchangeOrderRequest
	at zio.temporal.protobuf.ScalapbPayloadConverter.getCompanion$$anonfun$1(ScalapbPayloadConverter.scala:158)
	at scala.collection.immutable.HashMap.getOrElse(HashMap.scala:678)
	at zio.temporal.protobuf.ScalapbPayloadConverter.getCompanion(ScalapbPayloadConverter.scala:158)
	at zio.temporal.protobuf.ScalapbPayloadConverter.fromData(ScalapbPayloadConverter.scala:113)
	at io.temporal.common.converter.DefaultDataConverter.fromPayload(DefaultDataConverter.java:136)
	... 12 common frames omitted
15:39:58.774 [workflow-method-10b07a55-347f-4119-9b59-b1e4edffcc14-53a41b05-e116-4b6e-9af1-d92f2cf6c16c] ERROR i.t.i.sync.WorkflowExecuteRunnable - Workflow execution failure WorkflowId=10b07a55-347f-4119-9b59-b1e4edffcc14, RunId=53a41b05-e116-4b6e-9af1-d92f2cf6c16c, WorkflowType=ExchangeWorkflow
io.temporal.common.converter.DataConverterException: Unable to convert metadata {
  key: "encoding"
  value: "binary/protobuf"
}
metadata {
  key: "messageType"
  value: "com.cryptostock.exchange.ExchangeOrderRequest"
}
data: "\n\022\t\344N\026\214\235!\315\356\021\307\220#\267;$\027\252\022\b\b\001\022\004\n\002\001\244\030\000"
 to com.cryptostock.exchange.ExchangeOrderRequest when parsing:"
	�N��!��ǐ#�;$�
�" into following types: [class com.cryptostock.exchange.ExchangeOrderRequest]
	at io.temporal.common.converter.DefaultDataConverter.fromPayload(DefaultDataConverter.java:140)
	at io.temporal.common.converter.DataConverter.arrayFromPayloads(DataConverter.java:105)
	at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:278)
	at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:68)
	at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:135)
	at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:102)
	at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107)
	at io.temporal.worker.WorkerFactory.lambda$newWorkflowThreadExecutor$7(WorkerFactory.java:392)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: zio.temporal.protobuf.ProtobufPayloadException: Unable to convert metadata {
  key: "encoding"
  value: "binary/protobuf"
}
metadata {
  key: "messageType"
  value: "com.cryptostock.exchange.ExchangeOrderRequest"
}
data: "\n\022\t\344N\026\214\235!\315\356\021\307\220#\267;$\027\252\022\b\b\001\022\004\n\002\001\244\030\000"
 to com.cryptostock.exchange.ExchangeOrderRequest
	at zio.temporal.protobuf.ScalapbPayloadConverter.getCompanion$$anonfun$1(ScalapbPayloadConverter.scala:158)
	at scala.collection.immutable.HashMap.getOrElse(HashMap.scala:678)
	at zio.temporal.protobuf.ScalapbPayloadConverter.getCompanion(ScalapbPayloadConverter.scala:158)
	at zio.temporal.protobuf.ScalapbPayloadConverter.fromData(ScalapbPayloadConverter.scala:113)
	at io.temporal.common.converter.DefaultDataConverter.fromPayload(DefaultDataConverter.java:136)
	... 12 common frames omitted
```

The build.sc file is below:

```scala
import mill._, mill.scalalib._, mill.scalalib.scalafmt._
import $ivy.`com.lihaoyi::mill-contrib-scalapblib:`, contrib.scalapblib._

object versions {
  val scala3      = "3.1.2"
  val zio         = "2.0.0"
  val ziologging  = "2.0.0"
  val ziotemporal = "0.1.0-RC5"
}

object cryptostock extends SbtModule with ScalafmtModule with ScalaPBModule {
  def scalaVersion = versions.scala3
  def ivyDeps = Agg(
    ivy"dev.zio::zio:${versions.zio}",
    ivy"dev.zio::zio-logging:${versions.ziologging}",
    ivy"dev.zio::zio-logging-slf4j:${versions.ziologging}",
    ivy"dev.vhonta::zio-temporal-core:${versions.ziotemporal}",
    ivy"dev.vhonta::zio-temporal-protobuf:${versions.ziotemporal}",
    ivy"com.thesamet.scalapb::scalapb-runtime:0.11.11",
    ivy"ch.qos.logback:logback-classic:1.2.11"
  )
  object test extends Tests {
    def testFramework = T("zio.test.sbt.ZTestFramework")
    def ivyDeps = Agg(
      ivy"dev.zio::zio-test:${versions.zio}",
      ivy"dev.zio::zio-test-sbt:${versions.zio}",
      ivy"dev.vhonta::zio-temporal-testkit:${versions.ziotemporal}"
    )
  }
  def scalaPBVersion = "0.11.11"
  def scalaPBSources = T.sources {
    millSourcePath / "src" / "main" / "protobuf"
  }
  def scalaPBIncludePath = T.sources(Seq(scalaPBUnpackProto()))
  def scalaPBFlatPackage = true
  def scalaPBGrpc        = false
}
```

**Comment by vitaliihonta** [comment]
Have the same issue with sbt-native-packager. May be related to https://github.com/ronmamo/reflections/issues/373
TODO for myself: try `ClasspathHelper.forJavaClassPath` and concatenate it with `ClasspathHelper.forClassLoader`

**Comment by vitaliihonta** [comment]
@carlosedp could you try running the same example, but with 0.2.0-RC1 ?
I had a similar problem with my dockerized setup and it's gone with my latest fix

**Comment by carlosedp** [comment]
Gonna try this tomorrow! Thanks!!

**Comment by carlosedp** [comment]
Yay! Got some time and tested it out!

A couple adjustments were needed in the cryptostock to work on latest 0.2.0 (I'll submit a PR for that) and only got some warnings, other than that it worked!!

```
❯ ./mill -i show cryptostock.run
[1/1] show > [67/67] cryptostock.run
18:42:58.992 [ZScheduler-Worker-3] TRACE z.t.p.i.ProtoFileObjectAutoLoader$ - Provided exclude prefixes: [org/scalatools/,com.google.protobuf,com/google/type/,sbt,com.uber.m3,gogoproto/,com.google.geo,magnolia,org/codehaus/mojo/,com/google/longrunning/,com.cronutils,com.google.thirdparty,xsbt/,com.typesafe.config,distage,com/google/rpc/,logstage/,com/google/common/,akka/,com/thoughtworks/,com.google.logging,org/checkerframework/,zio/temporal/,org.slf4j,com/sun/,io/perfmark/,akka,android/,io.temporal,org.checkerframework,sun,com.google.api,com/google/errorprone/,com/cronutils/,org.scalatools,com/google/geo/,com.google.rpc,com.sun,org.LatencyUtils,izumi,org.reflections,com.google.errorprone,xsbti,xsbti/,sbt/,com/fasterxml/,logstage,pureconfig/,pureconfig,scala/,org/reflections/,com.thoughtworks,com/google/protobuf/,java,com/google/cloud/,com.google.common,com/uber/m3/,jdk/,cats/,izumi/,com.google.longrunning,javax,org/LatencyUtils/,org/slf4j/,org.codehaus.mojo,com.google.gson,org.HdrHistogram,com/google/logging/,com/google/gson/,com/typesafe/config/,io.grpc,zio,xsbt,net/sf/cglib/,io/micrometer/,com.google.type,javax/,com/google/api/,scala,magnolia/,zio/,sun/,io.micrometer,org/HdrHistogram/,com/google/thirdparty/,io.perfmark,mercator,io/temporal/,com.google.cloud,zio.temporal,cats,mercator/,META-INF,org/apache/ivy/,java/,org.apache.ivy,distage/,io/grpc/,com.fasterxml,jdk,module-info.class,META-INF/,gogoproto,android,net.sf.cglib]
18:42:59.228 [ForkJoinPool.commonPool-worker-23] WARN  org.reflections.Reflections - could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/home/carlosedp/repos/func-scala-2022-zio-temporal/cryptostock/compile-resources]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:113)
        at org.reflections.vfs.Vfs.fromURL(Vfs.java:95)
        at org.reflections.Reflections.lambda$scan$2(Reflections.java:176)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
18:42:59.363 [zio-default-blocking-1] INFO  i.t.s.WorkflowServiceStubsImpl - Created WorkflowServiceStubs for channel: ManagedChannelOrphanWrapper{delegate=ManagedChannelImpl{logId=1, target=127.0.0.1:7233}}
18:42:59.371 [ZScheduler-Worker-3] INFO  org.reflections.Reflections - Reflections took 337 ms to scan 60 urls, producing 199 keys and 703 values
18:42:59.439 [ZScheduler-Worker-3] TRACE z.t.p.i.ProtoFileObjectAutoLoader$ - Found subtypes of GeneratedFileObject: [class com.cryptostock.exchange.ExchangeProto$]
18:42:59.556 [ZScheduler-Worker-3] INFO  z.t.p.i.ProtoFileObjectAutoLoader$ - Loaded 1 GeneratedFileObject(s): [GeneratedFileObject(class=com.cryptostock.exchange.ExchangeProto$, file=exchange.proto)]
18:43:00.279 [zio-default-blocking-1] INFO  zio.temporal.worker.ZWorkerFactory - ZWorkerFactory started
18:43:00.285 [zio-default-blocking-1] INFO  com.cryptostock.Main.run - Going to create an exchange order
18:43:00.326 [zio-default-blocking-1] INFO  c.c.clients.ExchangeClientService - Going to trigger workflow
18:43:00.492 [zio-default-blocking-1] INFO  com.cryptostock.Main.run - Order placed
18:43:00.711 [workflow-method-0f8799c1-a609-4f26-abb2-ae92ac88f98f-6d140f7d-e1fe-445f-9b57-6a6ed0669c0b] INFO  c.c.workflows.ExchangeWorkflowImpl - Received order id=0f8799c1-a609-4f26-abb2-ae92ac88f98f
18:43:00.812 [Activity Executor taskQueue="exchanger", namespace="default": 1] INFO  c.c.w.ExchangeOrderActivityImpl - Hey, who wanna buy 42.0 CrabsCoins? Order id is 0f8799c1-a609-4f26-abb2-ae92ac88f98f, seller is 9ec68f9f-6007-4208-b8eb-2ceed3505483
18:43:00.816 [zio-default-blocking-1] INFO  com.cryptostock.Main.run.exampleFlow - --- Current order status Created
18:43:00.869 [workflow-method-0f8799c1-a609-4f26-abb2-ae92ac88f98f-6d140f7d-e1fe-445f-9b57-6a6ed0669c0b] INFO  c.c.workflows.ExchangeWorkflowImpl - Waiting for order to be accepted
18:43:02.571 [signal acceptExchangeOrder] INFO  c.c.workflows.ExchangeWorkflowImpl - Order accepted!
18:43:02.572 [workflow-method-0f8799c1-a609-4f26-abb2-ae92ac88f98f-6d140f7d-e1fe-445f-9b57-6a6ed0669c0b] INFO  c.c.workflows.ExchangeWorkflowImpl - Order accepted
18:43:02.613 [Activity Executor taskQueue="exchanger", namespace="default": 1] INFO  c.c.w.ExchangeOrderActivityImpl - Order 0f8799c1-a609-4f26-abb2-ae92ac88f98f accepted by b6d0b114-8fa8-47d6-91f3-7363bd26851b
18:43:02.701 [Activity Executor taskQueue="exchanger", namespace="default": 1] INFO  c.c.w.ExchangeOrderActivityImpl - Holding crypto funds orderId=0f8799c1-a609-4f26-abb2-ae92ac88f98f...
18:43:03.753 [Activity Executor taskQueue="exchanger", namespace="default": 1] INFO  c.c.w.ExchangeOrderActivityImpl - Holding crypto funds orderId=0f8799c1-a609-4f26-abb2-ae92ac88f98f...
18:43:03.756 [Activity Executor taskQueue="exchanger", namespace="default": 1] INFO  c.c.w.ExchangeOrderActivityImpl - Order 0f8799c1-a609-4f26-abb2-ae92ac88f98f amount held for the buyer
18:43:03.814 [workflow-method-0f8799c1-a609-4f26-abb2-ae92ac88f98f-6d140f7d-e1fe-445f-9b57-6a6ed0669c0b] INFO  c.c.workflows.ExchangeWorkflowImpl - Waiting for buyer confirmation...
18:43:04.591 [signal buyerTransferConfirmation] INFO  c.c.workflows.ExchangeWorkflowImpl - Buyer confirmation received!
18:43:04.592 [workflow-method-0f8799c1-a609-4f26-abb2-ae92ac88f98f-6d140f7d-e1fe-445f-9b57-6a6ed0669c0b] INFO  c.c.workflows.ExchangeWorkflowImpl - Buyer confirmed
18:43:04.662 [Activity Executor taskQueue="exchanger", namespace="default": 1] INFO  c.c.w.ExchangeOrderActivityImpl - Order 0f8799c1-a609-4f26-abb2-ae92ac88f98f payed by buyer screenshot=https://example.com
18:43:04.709 [workflow-method-0f8799c1-a609-4f26-abb2-ae92ac88f98f-6d140f7d-e1fe-445f-9b57-6a6ed0669c0b] INFO  c.c.workflows.ExchangeWorkflowImpl - Waiting for seller confirmation...
18:43:05.860 [zio-default-blocking-1] INFO  com.cryptostock.Main.run.exampleFlow - --- Current order status ConfirmedByBuyer
18:43:06.620 [signal sellerTransferConfirmation] INFO  c.c.workflows.ExchangeWorkflowImpl - Seller confirmation received!
18:43:06.622 [workflow-method-0f8799c1-a609-4f26-abb2-ae92ac88f98f-6d140f7d-e1fe-445f-9b57-6a6ed0669c0b] INFO  c.c.workflows.ExchangeWorkflowImpl - Seller confirmed
18:43:06.623 [workflow-method-0f8799c1-a609-4f26-abb2-ae92ac88f98f-6d140f7d-e1fe-445f-9b57-6a6ed0669c0b] INFO  c.c.workflows.ExchangeWorkflowImpl - Crypto transferred
18:43:06.665 [Activity Executor taskQueue="exchanger", namespace="default": 1] INFO  c.c.w.ExchangeOrderActivityImpl - Transferring crypto funds orderId=0f8799c1-a609-4f26-abb2-ae92ac88f98f...
18:43:06.670 [Activity Executor taskQueue="exchanger", namespace="default": 1] INFO  c.c.w.ExchangeOrderActivityImpl - Order id=0f8799c1-a609-4f26-abb2-ae92ac88f98f complete
18:43:06.784 [zio-default-blocking-1] INFO  com.cryptostock.Main.run - Exchange finished result=ExchangeOrder(0f8799c1-a609-4f26-abb2-ae92ac88f98f,Some(9ec68f9f-6007-4208-b8eb-2ceed3505483),Some(42.0),Some(CrabsCoin),Completed,Some(ExchangeOrderBuyer(b6d0b114-8fa8-47d6-91f3-7363bd26851b,Some(https://example.com))))
18:43:06.808 [zio-default-blocking-1] INFO  i.t.s.WorkflowServiceStubsImpl - shutdownNow
18:43:06.818 [zio-default-blocking-1] INFO  zio.temporal.worker.ZWorkerFactory - ZWorkerFactory shutdownNow initiated...
18:43:06.820 [zio-default-blocking-1] INFO  io.temporal.worker.WorkerFactory - shutdownNow: WorkerFactory{identity=15336@CarlosEDP-Win}
18:43:06.835 [zio-default-blocking-1] INFO  i.t.s.WorkflowServiceStubsImpl - shutdownNow
null
```

Thanks, I'll update the Mill PR as well!

**Comment by vitaliihonta** [comment]
I'll address the noisy log in #67
