### ISSUE TITLE
Research GraalVM native image compatability

### ISSUE THREAD

**Issue by vitaliihonta** [vitaliihonta/zio-temporal#91]
Take a look at @carlosedp example here https://github.com/carlosedp/zio-temporal-hello/tree/main/shared/resources/META-INF/native-image

I believe it could be handled somehow

**Comment by carlosedp** [comment]
While the `native-image.properties` initialization flags had to be added by hand, most json config files could be generated dynamically by using GraalVM native-image tracing agent.

The biggest quirk is that when I generate this metadata by using an e2e test, a mock temporal server is used so the agent apparently doesn't hit the GRPC classes not including them in the metadata so the generated binary fails.

When the metadata is generated with a real run of the worker and a real workflow execution, the binary works (supposedly all classes are found).

Some refs:

- Tracing agent docs: https://www.graalvm.org/22.0/reference-manual/native-image/Agent/
- How I run the agent in my project: https://github.com/carlosedp/zio-temporal-hello/blob/3f33c09d6cf2cec201eec5b3bf8d3e33fc172481/build.sc#L52C12-L57C4
- Temporal have some configs: https://github.com/temporalio/sdk-java/tree/master/temporal-serviceclient/src/main/resources/META-INF/native-image/io/temporal/temporal-serviceclient
- Some discussion on GraalVM repo: https://github.com/oracle/graal/issues/6452


Binary error when running with the e2e generated metadata:

```
❯ /Users/cdepaula/repos/scala/zio-temporal-hello/out/worker/nativeImage.dest/ziotemporalworker
timestamp=2023-07-04T16:48:15.521712-03:00 level=INFO thread=zio-fiber-6 message="HTTP Metrics Server started at http://localhost:8082/metrics" source=<empty>.Main.run
timestamp=2023-07-04T16:48:15.522017-03:00 level=INFO thread=zio-fiber-6 message="Started sample-worker listening to queue echo-queue" source=<empty>.Worker
timestamp=2023-07-04T16:48:15.538768-03:00 level=INFO thread=zio-fiber-6 message="ZWorkerFactory started" source=zio.temporal.worker.ZWorkerFactory
timestamp=2023-07-04T16:48:19.862526-03:00 level=DEBUG thread=zio-fiber-303 message="Received from null, message: CLI Msg" source=<empty>.EchoActivityImpl
timestamp=2023-07-04T16:48:19.862697-03:00 level=DEBUG thread=zio-fiber-303 message="Worker: Generated percent is 45" source=<empty>.EchoActivityImpl
timestamp=2023-07-04T16:48:19.862785-03:00 level=ERROR thread=zio-fiber-303 message="Worker: eventuallyFail - Failed to process message" source=<empty>.EchoActivityImpl
timestamp=2023-07-04T16:48:19.86304-03:00  level=DEBUG thread=zio-fiber-303 message="Fiber zio-fiber-303 did not handle an error" cause=Exception in thread "zio-fiber-303" scala.util.Right: Right(java.lang.Exception: Worker: ERROR: ACK: CLI Msg)
	at zio.temporal.internal.ZioUnsafeFacade.unsafeRunAsyncZIO.errorsHandled(ZioUnsafeFacade.scala:18)
	at zio.temporal.internal.ZioUnsafeFacade.unsafeRunAsyncZIO.fiber(ZioUnsafeFacade.scala:20) source=zio.temporal.internal.ZioUnsafeFacade.unsafeRunAsyncZIO
timestamp=2023-07-04T16:48:19.86381-03:00  level=WARN thread=zio-fiber-311 message="Activity failure. ActivityId=04a32ab1-ec26-35d2-86de-dbb0e83ec6c8, activityType=Echo, attempt=1" cause=Exception in thread "zio-fiber-" io.temporal.client.ActivityCompletionFailureException: null
	at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.fail(ManualActivityCompletionClientImpl.java:171)
	at io.temporal.client.ActivityCompletionClientImpl.completeExceptionally(ActivityCompletionClientImpl.java:73)
	at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
	at io.temporal.internal.WorkflowThreadMarker.lambda$protectFromWorkflowThread$1(WorkflowThreadMarker.java:83)
	at jdk.proxy4/jdk.proxy4.$Proxy48.completeExceptionally(Unknown Source)
	at zio.temporal.activity.ZActivity$.runAsyncImpl$$anonfun$2(ZActivity.scala:113)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at zio.temporal.internal.ZioUnsafeFacade$.unsafeRunAsyncZIO$$anonfun$1$$anonfun$1(ZioUnsafeFacade.scala:25)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	Suppressed: java.lang.RuntimeException: Generated message class "io.temporal.api.workflowservice.v1.RespondActivityTaskFailedRequest" missing method "getTaskToken".
		at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1929)
		at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
		at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2260)
		at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2334)
		at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:2064)
		at io.temporal.api.workflowservice.v1.RespondActivityTaskFailedRequest.internalGetFieldAccessorTable(RespondActivityTaskFailedRequest.java:126)
		at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
		at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:364)
		at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:354)
		at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:619)
		at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:111)
		at java.base@17.0.7/java.lang.String.valueOf(String.java:4216)
		at java.base@17.0.7/java.lang.StringBuilder.append(StringBuilder.java:173)
		at io.temporal.serviceclient.GrpcTracingInterceptor$1.sendMessage(GrpcTracingInterceptor.java:53)
		at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
		at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
		at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:317)
		at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:227)
		at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:154)
		at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskFailed(WorkflowServiceGrpc.java:3868)
		at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.lambda$fail$2(ManualActivityCompletionClientImpl.java:163)
		at io.temporal.internal.retryer.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:52)
		at io.temporal.internal.retryer.GrpcSyncRetryer.retry(GrpcSyncRetryer.java:69)
		at io.temporal.internal.retryer.GrpcRetryer.retryWithResult(GrpcRetryer.java:60)
		at io.temporal.internal.retryer.GrpcRetryer.retry(GrpcRetryer.java:50)
		at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.fail(ManualActivityCompletionClientImpl.java:158)
		at io.temporal.client.ActivityCompletionClientImpl.completeExceptionally(ActivityCompletionClientImpl.java:73)
		at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
		at io.temporal.internal.WorkflowThreadMarker.lambda$protectFromWorkflowThread$1(WorkflowThreadMarker.java:83)
		at jdk.proxy4/jdk.proxy4.$Proxy48.completeExceptionally(Unknown Source)
		at zio.temporal.activity.ZActivity$.runAsyncImpl$$anonfun$2(ZActivity.scala:113)
		at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
		at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
		at zio.temporal.internal.ZioUnsafeFacade$.unsafeRunAsyncZIO$$anonfun$1$$anonfun$1(ZioUnsafeFacade.scala:25)
		at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
		at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
		Suppressed: java.lang.NoSuchMethodException: io.temporal.api.workflowservice.v1.RespondActivityTaskFailedRequest.getTaskToken()
			at java.base@17.0.7/java.lang.Class.getMethod(DynamicHub.java:2227)
			at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1926)
			at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
			at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2260)
			at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2334)
			at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:2064)
			at io.temporal.api.workflowservice.v1.RespondActivityTaskFailedRequest.internalGetFieldAccessorTable(RespondActivityTaskFailedRequest.java:126)
			at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:133)
			at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:364)
			at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:354)
			at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:619)
			at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:111)
			at java.base@17.0.7/java.lang.String.valueOf(String.java:4216)
			at java.base@17.0.7/java.lang.StringBuilder.append(StringBuilder.java:173)
			at io.temporal.serviceclient.GrpcTracingInterceptor$1.sendMessage(GrpcTracingInterceptor.java:53)
			at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
			at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:37)
			at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:317)
			at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:227)
			at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:154)
			at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskFailed(WorkflowServiceGrpc.java:3868)
			at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.lambda$fail$2(ManualActivityCompletionClientImpl.java:163)
			at io.temporal.internal.retryer.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:52)
			at io.temporal.internal.retryer.GrpcSyncRetryer.retry(GrpcSyncRetryer.java:69)
			at io.temporal.internal.retryer.GrpcRetryer.retryWithResult(GrpcRetryer.java:60)
			at io.temporal.internal.retryer.GrpcRetryer.retry(GrpcRetryer.java:50)
			at io.temporal.internal.client.external.ManualActivityCompletionClientImpl.fail(ManualActivityCompletionClientImpl.java:158)
			at io.temporal.client.ActivityCompletionClientImpl.completeExceptionally(ActivityCompletionClientImpl.java:73)
			at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
			at io.temporal.internal.WorkflowThreadMarker.lambda$protectFromWorkflowThread$1(WorkflowThreadMarker.java:83)
			at jdk.proxy4/jdk.proxy4.$Proxy48.completeExceptionally(Unknown Source)
			at zio.temporal.activity.ZActivity$.runAsyncImpl$$anonfun$2(ZActivity.scala:113)
			at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
			at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
			at zio.temporal.internal.ZioUnsafeFacade$.unsafeRunAsyncZIO$$anonfun$1$$anonfun$1(ZioUnsafeFacade.scala:25)
			at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
			at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10) source=io.temporal.internal.activity.ActivityTaskExecutors$ActivityTaskExecutor
```

**Comment by carlosedp** [comment]
Most flags from the `native-image.properties` had to be added after I enabled the `zio-logging-slf4j2-bridge`... if you look into [this](https://github.com/carlosedp/zio-temporal-hello/commit/b5611757acded3219618510d443d24060fd51b16#diff-21d6c37988f8b3a0c325c2b4d542abbd08dc2453e521b23012c05fe23fed1cee) commit, all the flags that were added were required after adding the log lib. The native-image binary worked with the existing ones previous to this commit if not using the log lib.

My big gripe is where all this initialization flags should be?

- Temporal java-sdk
- Zio-temporal
- slf4j
- ???

@Spikhalskiy, would you take a look at this since you worked on GraalVM in Temporal SDK?

**Comment by carlosedp** [comment]
On talks with GraalVM guys (https://twitter.com/carlosedp/status/1675945560119865350), I found that all classes are initialized at run-time by default so looking at GraalVM PRs, I found https://github.com/oracle/graal/pull/3179/files that added a flag to exclude configs from regexes. 

Since a lot of libs bundle initialization rules, I've added to my native-image build the flag regex'ing out all `.properties` from all jars to bypass the initialize flags from them and also removed all flags added to the project locally.

In the end I've successfully built the native-image tackling one of the issues listed above. The other one is how to properly generate the json metadata automatically.

Since zio-temporal also uses reflection, I don't think bundling this into the library solves since the user's workflows and activities should also be added as it can be seen in https://github.com/carlosedp/zio-temporal-hello/blob/3f33c09d6cf2cec201eec5b3bf8d3e33fc172481/shared/resources/META-INF/native-image/proxy-config.json#L18-L21.

Here's the PR removing the flags and excluding lib configs: https://github.com/carlosedp/zio-temporal-hello/pull/4

**Comment by carlosedp** [comment]
Last commit to my sample app added some missing reflection/proxy classes: https://github.com/carlosedp/zio-temporal-hello/commit/793d3ec781874b8bc09c7cf459b0ee872480fa27

**Comment by carlosedp** [comment]
Kinda got a false-positive on https://github.com/vitaliihonta/zio-temporal/issues/91#issuecomment-1620840841 where I've removed all initialization flags replacing by a config to exclude the properties from JARs. 

The image was built successfully but once I've tried to access the app's HTTP server (based on zio-http which uses netty) I got the error:

```
❯ ./out/worker/nativeImage.dest/ziotemporalworker
timestamp=2023-07-12T18:19:58.639298-03:00 level=INFO thread=zio-fiber-6 message="HTTP Metrics Server started at http://localhost:8082/metrics" source=<empty>.Main.run
timestamp=2023-07-12T18:19:58.63969-03:00  level=INFO thread=zio-fiber-6 message="Started sample-worker listening to queue echo-queue" source=<empty>.Worker
timestamp=2023-07-12T18:19:58.670852-03:00 level=INFO thread=zio-fiber-6 message="ZWorkerFactory started" source=zio.temporal.worker.ZWorkerFactory
timestamp=2023-07-12T18:24:37.391004-03:00 level=WARN thread=zio-fiber-785 message="An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception." cause=Exception in thread "zio-fiber-" java.lang.ExceptionInInitializerError: null
	at io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:417)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.kqueue.AbstractKQueueServerChannel$KQueueServerSocketUnsafe.readReady(AbstractKQueueServerChannel.java:112)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:387)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:213)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:291)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
	Suppressed: java.lang.IllegalArgumentException: Can't find '[touch]' in io.netty.util.ReferenceCountUtil
		at io.netty.util.ResourceLeakDetector.addExclusions(ResourceLeakDetector.java:596)
		at io.netty.util.ReferenceCountUtil.<clinit>(ReferenceCountUtil.java:31)
		at io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:417)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.kqueue.AbstractKQueueServerChannel$KQueueServerSocketUnsafe.readReady(AbstractKQueueServerChannel.java:112)
		at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:387)
		at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:213)
		at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:291)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203) source=io.netty.channel.DefaultChannelPipeline
```

And the app doesn't respond of return the HTTP request. Back to step 0.

**Comment by thomaswue** [comment]
Are you using the default metadata for Netty as available at https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata/io.netty/netty-common? What Netty version are you using?

The error indicates that there is a missing reflection entry for:
```
{
    "condition": {
      "typeReachable": "io.netty.util.ReferenceCountUtil"
    },
    "name": "io.netty.util.ReferenceCountUtil",
    "queryAllDeclaredMethods": true
}
```

Netty uses a lot of complex reflection in static constructors. If you initialize those classes at build time, the configuration is not required. It is still recommended to rather configure than initialize at build time.

**Comment by carlosedp** [comment]
Tried to consolidate the steps I use to generate all metadata for GraalVM in my project: https://github.com/carlosedp/zio-temporal-hello/issues/5

**Comment by thomaswue** [comment]
OK, cool! Starting from netty 5, the metadata is directly included in the netty JAR file itself to avoid that problem. Can you maybe create a pull request at https://github.com/oracle/graalvm-reachability-metadata with the 4.1.93 netty data?

**Comment by guizmaii** [comment]
FYI, the Agent way is not working for me, nor the `graalvm-reachability-metadata` way, nor the combination of both (copying the `*-config.json` from the metadata repo and then running the Agent to update the copied configs).
My extremely minimal project refuses to compile with these settings

I only have 2 dependencies: Netty (`4.1.94`, inherited from zio-http) and Logback

What is "working" is to use these `native-image` options: `native-image --no-fallback ... --initialize-at-run-time=io.netty --initialize-at-build-time=org.slf4j,ch.qos.logback`
It's "working" because it's compiling the code and generating the executable binary but my program crashes when it's using Netty at runtime.
My program is a CLI. I can launch some commands of the CLI but the ones involving Netty crashes with the following error:
```scala
$ ./my-cli say-hello
00:52:29.427 [ZScheduler-Worker-10] ERROR zio-slf4j-logger - 
java.lang.ExceptionInInitializerError: null
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at io.netty.util.internal.PlatformDependent$Mpsc.newMpscQueue(PlatformDependent.java:1029)
        at io.netty.util.internal.PlatformDependent.newMpscQueue(PlatformDependent.java:1040)
        at io.netty.channel.nio.NioEventLoop.newTaskQueue0(NioEventLoop.java:283)
        at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:154)
Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: producerIndex
        at io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:111)
        at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueueProducerFields.<clinit>(BaseMpscLinkedArrayQueue.java:55)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at io.netty.util.internal.PlatformDependent$Mpsc.newMpscQueue(PlatformDependent.java:1029)
        at io.netty.util.internal.PlatformDependent.newMpscQueue(PlatformDependent.java:1040)
Caused by: java.lang.NoSuchFieldException: producerIndex
        at java.base@20.0.1/java.lang.Class.checkField(DynamicHub.java:1004)
        at java.base@20.0.1/java.lang.Class.getDeclaredField(DynamicHub.java:1119)
        at io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess.fieldOffset(UnsafeAccess.java:107)
        at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueueProducerFields.<clinit>(BaseMpscLinkedArrayQueue.java:55)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
        at java.base@20.0.1/java.lang.Class.ensureInitialized(DynamicHub.java:579)
```

Any idea how to fix this @thomaswue @carlosedp maybe? 🤔

**Comment by carlosedp** [comment]
The usage of `graalvm-reachability-metadata` highly depends on the version of the lib. It won't help with zio-http since the metadata added to the repo is for netty 4.1.80 and zio-http uses a newer one. Also the lib only adds the proxy and reflection metadata.

Now on to the initialization, what happens is that netty/logback changes some initialization to build-time in it's own metadata so you might need to override or ignore it like I did in my app here: https://github.com/carlosedp/zio-temporal-hello/blob/32adb3de5f0e724833e3a1bb28089d9f50fb8b0c/build.sc#L74C7-L74C7

If you have the link to the sample app, I could look at it to help :)

**Comment by carlosedp** [comment]
There you go @guizmaii ... a sample app with zio-http and logback which can generate a native-image... I added all configuration needed in the scala file itself so it can be run with scala-cli.

https://gist.github.com/carlosedp/6547bc730899995683442916bb225876

**Comment by guizmaii** [comment]
@carlosedp what is this configuration for/about `-Djdk.http.auth.tunneling.disabledSchemes=`? 🤔

**Comment by carlosedp** [comment]
Apparently you are using Graal 20 and the `--exclude-config` is available from Graal 23.

The "Classes that should be initialized at run time got initialized during image building" error is because netty and/or logback are initializing some classes at build-time with their own metadata, the exclude-config should override this. Also you don't need the `--initialize-at-runtime` anymore with it since initialization on runtime is default for all classes.

According to Oracle docs, the `-Djdk.http.auth.tunneling.disabledSchemes` is:

> Disable Basic authentication for HTTPS tunneling
> In some environments, certain authentication schemes may be undesirable when proxying HTTPS. Accordingly, the Basic authentication scheme has been deactivated, by default, in the Oracle Java Runtime, by adding Basic to the jdk.http.auth.tunneling.disabledSchemes networking property. Now, proxies requiring Basic authentication when setting up a tunnel for HTTPS will no longer succeed by default. If required, this authentication scheme can be reactivated by removing Basic from the jdk.http.auth.tunneling.disabledSchemes networking property, or by setting a system property of the same name to "" ( empty ) on the command line.
> 

Check my Gist, it contains the basics to make it all work with both logback and zio-http (which uses netty).
